# Generated by Django 4.0.6 on 2022-07-08 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amazon_link', models.URLField(blank=True, null=True)),
                ('goodreads_link', models.URLField(blank=True, null=True)),
                ('read_online_link', models.URLField(blank=True, null=True)),
                ('amazon_rating', models.FloatField()),
                ('goodreads_rating', models.FloatField()),
                ('audiobook_available', models.BooleanField()),
                ('kindle_unlimited', models.BooleanField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookseries')),
            ],
        ),
    ]
