# Generated by Django 4.0.6 on 2022-07-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_audiobook_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookseries',
            name='goodreads_url',
            field=models.URLField(default='https://www.goodreads.com'),
            preserve_default=False,
        ),
    ]
