# Generated by Django 4.0.6 on 2022-07-08 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_bookseries_goodreads_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookseries",
            old_name="goodreads_url",
            new_name="goodreads_link",
        ),
    ]
