# Generated by Django 4.0.6 on 2022-07-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_rename_goodreads_url_bookseries_goodreads_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="amazon_rating_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="goodreads_rating_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
